services:
  # Serviço de Clientes
  client_service_api:
    build:
      context: ./client_service_api
      dockerfile: Dockerfile
    container_name: erp2-clients-api
    ports:
      - "8001:8001"
    volumes:
      - ./client_service_api:/app
    command: bash -c "export PYTHONPATH=/app && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    depends_on:
      db_clients:
        condition: service_healthy
    environment:
      - DATABASE_URL_CLIENTS=postgresql://postgres:postgres@erp2-db-clients:5432/clients_db
      
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp2-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - client_service_api # Agora depende apenas do serviço de clientes
    environment:
      # A URL da API de clientes para o frontend se conectar
      - REACT_APP_CLIENTS_API_URL=http://localhost:8001

  # Banco de Dados para Clientes
  db_clients:
    image: postgres:13
    container_name: erp2-db-clients
    volumes:
      - postgres_clients_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clients_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_clients_data:
